### ISSUE TITLE
Change memory to storage

### ISSUE THREAD

**Issue by tohrnii** [labdao/openlab-contracts#7]
https://github.com/labdao/openlab-contracts/blob/ec1f903bce08c9e8bea3464f03d993bef9d33bfc/contracts/Exchange.sol#L122
Change memory to storage to store the new value in persistent storage.

**Comment by tohrnii** [comment]
Also in
https://github.com/labdao/openlab-contracts/blob/ec1f903bce08c9e8bea3464f03d993bef9d33bfc/contracts/Exchange.sol#L114

**Comment by acashmoney** [comment]
@tohrnii my understanding is `Job memory job` saves gas for the user. Is this breaking functionality on the CLI integration?

**Comment by tohrnii** [comment]
@acashmoney Currently this is copying the storage variable to memory and modifying the copied object which is not persisted to the storage. Hence the job status is unchanged after the function call is over since the change in value is not persisted to the data. Creating a storage reference instead will directly refer the storage and modify the storage which will persist after the function call.

**Comment by acashmoney** [comment]
Thanks @tohrnii . Updating locally, changes will be reflected in next push to `main`
