### ISSUE TITLE
tutorial on how to deploy and interact with contracts on polygon with gnosis safe

### ISSUE THREAD

**Issue by NiklasTR** [labdao/openlab-contracts#9]

**Comment by blahah** [comment]
There are existing tutorials for these situations. We don't need to develop new tutorials unless the existing resources don't serve the need. Closing with some examples of what's already out there:

## Polygon

https://learn.figment.io/tutorials/deploying-and-debugging-smart-contracts-on-polygon

https://dev.to/akhileshthite/how-to-deploy-smart-contracts-on-polygon-matic-network-how-to-handle-different-errors-3l2k
